SET search_path TO core;
ALTER TABLE room_access ALTER COLUMN in_room TYPE BOOLEAN,  ALTER COLUMN in_room DROP DEFAULT;
ALTER TABLE room_access ADD PRIMARY KEY (parasite_id, room_id);
ALTER TABLE rooms ALTER COLUMN owner_id TYPE TEXT, ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE room_access DROP CONSTRAINT room_access_parasites_id_fk;
ALTER TABLE room_access ADD CONSTRAINT fk_room_access_parasite_id__id FOREIGN KEY (parasite_id) REFERENCES parasites(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE room_access DROP CONSTRAINT room_access_rooms_id_fk;
ALTER TABLE room_access ADD CONSTRAINT fk_room_access_room_id__id FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE room_invitations DROP CONSTRAINT room_invitations_rooms_id_fk;
ALTER TABLE room_invitations ADD CONSTRAINT fk_room_invitations_room_id__id FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE room_invitations DROP CONSTRAINT room_invitations_parasites_id_fk;
ALTER TABLE room_invitations ADD CONSTRAINT fk_room_invitations_invitee_id__id FOREIGN KEY (invitee_id) REFERENCES parasites(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE room_invitations DROP CONSTRAINT room_invitations_parasites_id_fk_2;
ALTER TABLE room_invitations ADD CONSTRAINT fk_room_invitations_sender_id__id FOREIGN KEY (sender_id) REFERENCES parasites(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE rooms DROP CONSTRAINT rooms_parasites_id_fk;
ALTER TABLE rooms ADD CONSTRAINT fk_rooms_owner_id__id FOREIGN KEY (owner_id) REFERENCES parasites(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
