ktor {
    deployment {
        port = 6969
        port = ${?PORT}
    }
    application {
        modules = [ net.chatalina.ApplicationKt.module ]
    }
}

encryption {
    public_key = "keys/pub.key"
    public_key = ${?PUBLIC_KEY}
    private_key = "keys/priv.key"
    private_key = ${?PRIVATE_KEY}
}

bec {
    client_domain = ${CLIENT_DOMAIN}
    client_ssl = false
}

jwt {
    jwks = ${OAUTH_JWKS_URL}
    issuer = ${OAUTH_ISSUER}
    audience = ${OAUTH_AUDIENCE}
}

db {
    url = "jdbc:postgresql://localhost:5432/"
    database = "chatalina"
    user = ${PG_USER}
    password = ${PG_PASS}
}
