ktor {
    deployment {
        port = 6969
        port = ${?PORT}
    }
    application {
        modules = [ net.chatalina.ApplicationKt.module ]
    }
}

bec {
    client_domain = ""
    client_ssl = false
}

jwt {
    jwks = ""
    issuer = ""
    audience = ""
}
